### PR TITLE
Add submission script

### PR DESCRIPTION
**Pull request by pinin4fjords**
This adds the small control script that submits https://github.com/ebi-gene-expression-group/scxa-control-workflow, via a cron job.

That workflow does most of the work in coordinating quantification work across experiments. This script just makes sure the most recent version of the component workflows have been downloaded, and where a workflow session completes without error, tidies up the Nextflow working directory.

### CODE REVIEW

**Comment by pcm32** [comment]
should we put this inside a `w_*_quantification` directory?

**Comment by pinin4fjords** [comment]
Well, this is a generic control thing not specific to a technology. What w_ prefix would we give it?

**Comment by pinin4fjords** [comment]
Script moved to subdir @pcm32 - all good?

**Comment by pinin4fjords** [comment]
@pcm32 I'm going to merge this while you're away since I want to use it in production. We can tweak later.

**Pull request merged**
