### PR TITLE
Improve cell_type_field annotation

### PR DESCRIPTION
**Pull request by pcm32**
This PR improves the annotation shown in the UI for the cell type field, to avoid the error related to different lengths of collections being fed into find_markers step.

### CODE REVIEW

**Comment by pcm32** [comment]
Missing to see where the default goes, bear with me.

**Comment by pcm32** [comment]
Both files load fine as workflows when done directly from the raw github.

**Comment by pcm32** [comment]
Should mitigate #29

**Review by pinin4fjords — APPROVED** [review]
Looks good- thanks @pcm32

**Pull request merged**
