### PR TITLE
SCXA analysis workflow updates 2021

### PR DESCRIPTION
**Pull request by pinin4fjords**
This is the work-in progress to implement some workflow updates recommended to us by Chichau, subject to successful evaluation.

**Edit, September '21:**

Following [thorough evaluation](https://github.com/ebi-gene-expression-group/scanpy-parameter-explorer), the following changes were implemented:

Base param set:

- Switch to filter based on counts only, > 1500
- Add mitochondrial threshold of 35%
- Switch marker genes to Wilcoxon method 

Droplet experiments

- Add scaling step (required some wiring to do this but supply the un-scaled matrix to the marker genes step)
- Add Scrublet

For batched experiments

- Add batch to HVG step, alongside use of Harmony

SMART workflow: [here](http://hl-codon-03-01:8090/u/jon/w/scxa-prod-v025-scanpy-181-plate-imported-from-uploaded-file-1). 
Droplet workflow: [here](http://hl-codon-03-01:8090/u/jon/w/scxa-prod-v025-scanpy-181-droplet-imported-from-uploaded-file-1) .

### CODE REVIEW

**Comment by pinin4fjords** [comment]
Current changes ready to go, tested on droplet, plate, batched and unbatched

**Comment by pinin4fjords** [comment]
- Droplet pipeline available [here](http://hl-codon-03-01:8090/u/jon/w/scxa-prod-v025-scanpy-181-droplet-imported-from-uploaded-file)
- Plate pipeline available [here](http://hl-codon-03-01:8090/u/jon/w/scxa-prod-v025-scanpy-181-plate-imported-from-uploaded-file)

**Review by pcm32 — APPROVED** [review]
Great work!

**Comment by pinin4fjords** [comment]
Thanks @pcm32 !

**Pull request merged**
